version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo "Entering project directory"
      - cd cicd
      - echo "Java version:"
      - java -version
      - echo "Fix mvnw permissions"
      - chmod +x mvnw
      - echo "Running tests..."
      - ./mvnw -B test

  build:
    commands:
      - echo "Packaging jar..."
      - chmod +x mvnw
      - ./mvnw -B clean package -DskipTests

  post_build:
    commands:
      - echo "Preparing Elastic Beanstalk bundle..."
      - mkdir -p bundle
      - cp target/*.jar bundle/app.jar
      - |
        cat > bundle/Procfile <<'EOF'
        web: java -jar app.jar
        EOF
      - cd bundle
      - zip -r ../application.zip .
      - cd ..

artifacts:
  files:
    - cicd/application.zip